### ISSUE TITLE
Dashboard not detecting all Gitlab repositories under organization

### ISSUE THREAD

**Issue by alecgerona** [renovatebot/app-support#60] opened 2020-07-07 19:00 UTC
**What Renovate type are you using?**

Hosted App with Gitlab

**Describe the bug**
Hi, am trying to install renovate on a private repository on a private organization in Gitlab. I can add renovate bot manually through the members tab but the dashboard can't see the project at all. Or any projects under that directory for that matter. I can add the bot and it made the merge request that starts integration, but the webhook is still missing and it's still absent from the dashboard.

Do I need to do something for the dashboard to view all the repositories?

**Relevant debug logs**
Looking at the api calls the dashboard makes it throws a 404 every other call and the 200s are just OPTIONS calls with no response. 

**Additional context**
Looking at the repositories found by the crawl, only those on a specific directory are not being discovered by the dashboard.

**Comment by rarkins** [comment] 2020-07-07 19:14
Please provide:
- Screenshot of what you see when you load the dashboard
- Screenshot of the developer tools 404 messages (some of them are expected, some may not be)
- The name of one repository which is not working, or enough information to identify it

**Comment by alecgerona** [comment] 2020-07-07 19:38
Hmm. I'll try to block out the least since these are all private but on the left side menu I see the project that got discovered by the crawler that I added renovate to. When I click the gear it shows every project on every subgroup of our Gitlab organization except for one group. 

When I click the gear it starts the search loop and it's mostly 404 except for the one project I have installed renovate on and it never called the projects of the subgroup. I am the owner/admin of the subgroup and the whole organization actually. So this is really weird.

**Comment by rarkins** [comment] 2020-07-07 21:19
The client JS first calls `"projects?archived=false&min_access_level=40&per_page=100"` using your token/identity.

Then for each repository it finds, it checks if Renovate's identity has access. If it doesn't, then there's a 404 response.

It sounds like this might be caused by #35 ?

**Comment by alecgerona** [comment] 2020-07-08 02:53
Most probably. We have more than 100 repositories. Can we increase that?

**Comment by alecgerona** [comment] 2020-07-08 14:54
As a workaround, is it enough adding the bot manually through the project's members? I successfully received the integration MR. Will merging it add the webhook as well?

**Comment by rarkins** [comment] 2020-07-08 15:35
Webhooks can only be added by administrators so we decided not to ask for that permission and have not added the capability on our server side even if given permissions. Hence the only way to add the webhooks is upon login or install for the dashboard, because it's done using your personal oauth token and not stored. I'll look into whether we can handle pagination.

However renovate will still run ~hourly even without webhooks, if you add it as a developer.

**Comment by alecgerona** [comment] 2020-07-08 15:40
So I can safely merge the MR for now? The only con is updates run every hour instead of instantly with webhooks? Am I understanding this correctly?

**Comment by rarkins** [comment] 2020-07-08 16:40
Yes

**Comment by alecgerona** [comment] 2020-07-08 17:01
Great. Thanks. Might as well leave this issue open for when the pagination logic is implemented. Thank you!

**Comment by rarkins** [comment] 2020-07-08 17:04
We have #35 so let's close this. Please subscribe to the other

**Closed as completed** 2020-07-08 17:07 UTC
