### ISSUE TITLE
White Source Renovate Dashboard Doesn't Show All Repos in GitLab Organization

### ISSUE THREAD

**Issue by Raimmaster** [renovatebot/app-support#65] opened 2020-07-17 22:50 UTC
Hello, I've authenticated in https://app.renovatebot.com/dashboard with my GitLab user. I'm an organization owner and certain repos don't show up, specifically the one we're looking to use to try out the Renovate Bot.

For example the app has `web-app` in its title. ![Image](https://i.imgur.com/c4HHwhx.png)
However, after all projects have loaded, the organization shows up, some of the projects shows up, but not that one, as showcased while searching in the site: ![Projects](https://i.imgur.com/WAUQnVU.png)

What could be causing the issue that not all projects load, and how may this be solved? Is this a permissions error from my part, or a limitation of the dashboard? The closest issue I've found that's similar is this one but related to enabled repos: https://github.com/renovatebot/app-support/issues/6

Thanks beforehand for your support.

**Comment by rarkins** [comment] 2020-07-18 04:16
Could it be caused by #35 ?

**Comment by Raimmaster** [comment] 2020-07-20 03:34
It could be, yes. There are exactly 100 repos being shown, but not all the repos from the organization.

**Comment by rarkins** [comment] 2020-07-20 04:28
Closing as duplicate, please follow #35

**Closed as completed by rarkins** 2020-07-20 04:28 UTC
